[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "PAGBANK_TOKEN,PAGBANK_AMBIENTE"

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200
  force = true

[[redirects]]
  from = "/produto/*"
  to = "/.netlify/functions/produto/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/categoria/*"
  to = "/.netlify/functions/categoria/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/feed-google.xml"
  to = "/.netlify/functions/feed-google"
  status = 200
  force = true
